export default {
  AUTH_USER: 'AUTH_USER',
  UNAUTH_USER: 'UNAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_USER: 'GET_USER',
  GET_SMOOTHIE: 'GET_SMOOTHIE',
  EDIT_SMOOTHIE: 'EDIT_SMOOTHIE',
  DELETE_SMOOTHIE: 'DELETE_SMOOTHIE',
  LIKE_SMOOTHIE: 'LIKE_SMOOTHIE',
};
